name: Debug log

on: push

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - run: echo "::debug::This is a debug message"

      - run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
