name: Environments

on:
  workflow_dispatch:
    inputs:
      environment-name:
        description: "Environment name"
        required: true
        type: environment
        default: test

defaults:
  run:
    shell: bash

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}

    steps:
      - run: echo "Hello, ${USERNAME}"
