name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name}}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
